- openstack_hypervisor/api.py
- openstack_hypervisor/hooks.py
- openstack_hypervisor/model.py
- openstack_hypervisor/services.py
- setup.cfg
- snap/snapcraft.yaml
- templates/ceilometer.conf.j2
- templates/nova.conf.j2
- templates/polling.yaml.j2
- tests/unit/test_hooks.py
Add new service to run ceilometer agent polling
for compute node.
Add ceilometer configuration and polling template files. Add config to enable/disable the service and telemetry publish secret key.
Add system-observe to libvirtd in snapcraft.
> Add new service ceilometer-agent-compute

- openstack_hypervisor/api.py
- openstack_hypervisor/hooks.py
- openstack_hypervisor/model.py
- snap/snapcraft.yaml
As part of the COS integration, this PR adds the [libvirt exporter](https://github.com/Tinkoff/libvirt-exporter/tree/master) service to the snap, and also add snap configuration option to enable / disable exporter services. By default, the exporter services are disabled until the monitoring.enable is set to true.
Related to: https://review.opendev.org/c/openstack/charm-openstack-hypervisor/+/893007
PR Migrated from https://github.com/openstack-snaps/snap-openstack-hypervisor/pull/32
> Add libvirt exporter service

- openstack_hypervisor/hooks.py
- openstack_hypervisor/services.py
- setup.cfg
- snap/snapcraft.yaml
Create a python service object to run the ovs-exporter daemon
Currently it's a follow up PR for https://github.com/canonical/snap-openstack-hypervisor/pull/2
> feat(services): Add ovs exporter service

- templates/ceilometer.conf.j2
- templates/neutron.conf.j2
Use quorum queues for ceilometer-compute-agent
service. Update ceilometer.conf template with
quorum queues.
AMQP is not used by neutron-ovn-metadata-agent,
however for the completion of neutron.conf, add
quorum queues in the template.
> Use rabbit quorum queues for ceilometer

- openstack_hypervisor/model.py
- templates/nova.conf.j2
html5proxy_base_url is constructed based on spice-proxy-address with harcoded port. However with the use of loadbalancer for nova-spiceproxy, the URL may be based on name instead of ip and port can change. So add new config option spice-proxy-url in compute.
Deprecate existing config option spice-proxy-address. Disable vnc in nova.conf
> Add config option spice-proxy-url

- openstack_hypervisor/hooks.py
rabbitmq.url and network.ovn-sb-connection are required keys to for multiple services of the openstack-hypervisor snap. Unsetting them from the charm would only lead to default values being passed and the services being restarted.
This conflicts with previous work of removing rabbitmq's url or ovn-sb-connection to stop the services.
> Set rabbitmq and ovn sb connection as unset by default

- openstack_hypervisor/hooks.py
- templates/ceilometer.conf.j2
- templates/neutron.conf.j2
- templates/nova.conf.j2
Add condition on templating rabbitmq since it's unset by default. Early exit ovn configuration is the SB connection string is missing.
> Add condition on templating rabbitmq, early exit ovn if sb con missing

- snap/snapcraft.yaml
This feature[0] was merged in 2.61, which is needed for observability. Set it as minimum requirements for the snap.
0: https://github.com/snapcore/snapd/pull/13149
> Set a minimum version to snapd

- README.md
- openstack_hypervisor/hooks.py
- templates/nova.conf.j2
Add the option `compute.resume-on-boot` to resume guest instances when the host boots.
> Resume guest instances on boot

- snap/snapcraft.yaml
Fix: #23 
All the required files for exporter are inside SNAP_COMMON, so those plugins are not necessary
Below two files show the required files of ovs-exporter and how we change it to files inside SNAP_COMMON:
- [Required files for exporter](https://github.com/greenpau/ovsdb/blob/ba2fa6bc5e69ee5511f72847d060e6709036ae0f/ovs.go#L42)
- [Change configuration for exporter](https://github.com/canonical/snap-openstack-hypervisor/blob/17798d125db2637a76fc54214228bd6e3a8259b2/openstack_hypervisor/services.py#L195)
> fix: Remove unnessary plugins for ovs-exporter

- snap/snapcraft.yaml
ovs-dpctl needs net_admin (network-control).
virtlogd wants to ptrace the libvirtd proces (system-observe).
This resolves a few of the apparmor related messages generated from this snap as well as restoring functionality for tools.
> Add misc missing plugs

- README.md
- openstack_hypervisor/hooks.py
Gateway status can be derived from the configuration provided for the external gateway IP address and the external NIC.
Obsolete this configuration option and derive its value instead.
> Obsolete enable-gateway config

- openstack_hypervisor/hooks.py
When an NIC is provided for external networking, ensure that the link flag is set to up once it's added to the OVS bridge to make as much effort as possible to ensure external network connectivity.
> Ensure external nic interface is set to up

- snap/snapcraft.yaml
Qemu build on jammy updates fails with deprecated-declarations warning.
Add flag to disable making warning to errors.
Ubuntu qemu jammy/updates build also disables Werror [1]
[1] https://launchpadlibrarian.net/742807497/buildlog_ubuntu-jammy-amd64.qemu_1%3A6.2+dfsg-2ubuntu6.22_BUILDING.txt.gz
> Fix qemu build errors

- templates/nova.conf.j2
Add config compute_monitors in nova.conf and set it to cpu.virt_driver.
This helps in collecting compute node related metrics `compute.node.cpu.*` [1]
[1] https://docs.openstack.org/ceilometer/2024.1/admin/telemetry-measurements.html
> [nova] Add config compute_monitors

- templates/polling.yaml.j2
Metric memory.resident is required by watcher service.
So add the metric in the list of pollsters to be collected.
> Add memory.resident to ceilometer pollsters

- openstack_hypervisor/hooks.py
- requirements.txt
- tests/unit/conftest.py
- tests/unit/test_hooks.py
Starting libvirt on 24.04 based hosts fails because of missing TLS. This change will initialize a local TLS certificate, which will allow the hypervisor to run in TLS in standalone installations.
> Fix local tls

- openstack_hypervisor/cli/__init__.py
- openstack_hypervisor/cli/interfaces.py
- openstack_hypervisor/cli/log.py
- openstack_hypervisor/cli/main.py
- requirements.txt
- setup.cfg
- snap/snapcraft.yaml
- tests/unit/cli/test_interfaces.py
Add cli capabilities under the snap top-level name. Add a `list-nic` command to allow the snap returning the nics present, and which are candidates for being pulled in OVN/OVS.
Example:
```
root@microstack:~# openstack-hypervisor -v list-nics
DEBUG:openstack_hypervisor.cli.interfaces:Checking interface 'lo'
Checking interface 'lo'
DEBUG:openstack_hypervisor.cli.interfaces:Ignoring interface 'lo', it is a virtual interface, kind: None
Ignoring interface 'lo', it is a virtual interface, kind: None
DEBUG:openstack_hypervisor.cli.interfaces:Checking interface 'enp5s0'
Checking interface 'enp5s0'
DEBUG:openstack_hypervisor.cli.interfaces:Interface 'enp5s0' has IP address '10.206.54.100'
Interface 'enp5s0' has IP address '10.206.54.100'
DEBUG:openstack_hypervisor.cli.interfaces:Interface …
```
> Add list-nics cli

- openstack_hypervisor/cli/interfaces.py
- tests/unit/cli/test_interfaces.py
The openstack snap will prompt (in interactive mode) for confirmation when adding a configured nic candidate.
This commands returns in the structured format if a NIC is configured or not.
Tidy a bit format value output.
> Add configured interfaces as candidate

- requirements.txt
- setup.cfg
- snap/patches/libvirt/0001-Remove-definition-of-DNSMASQ.patch
- snap/snapcraft.yaml
- tox.ini
Upgrade packages to their 24.04 counterparts.
A patch in libvirt introduced a redefinition of DNSMASQ to the hardcoded value `dnsmasq`. Remove this from the sources to make sure the right DNSMASQ is used.
> Upgrade snap base to core24

- .github/workflows/build-and-test.yml
- openstack_hypervisor/hooks.py
- tests/unit/test_hooks.py
Ensure that all files are written without world read permission as they may contain credentials for accessing services.
> Enforce secure file permissions

- README.md
- openstack_hypervisor/hooks.py
- templates/nova.conf.j2
- tests/unit/test_hooks.py
* Add new config compute.flavors This is a placeholder to add compute flavors.
The value will be a list of comma separated flavors. Flavor name for AMD SEV is sev.
* Add new config sev.reserved-host-memory-mb to reserve memory for host
* Detect if AMD SEV is enabled at kernel param file and libvirtd domain capabilities
* Update compute.flavors with sev if AMD SEV is detected
* Update nova compute configurations if AMD SEV is enabled
> Add support for detection of AMD SEV

- openstack_hypervisor/hooks.py
- tests/unit/test_hooks.py
If the snap does not have the rights to read if SEV is enabled, handle it as unsupported.
> SEV: handle permission denied as not supported

- snap/snapcraft.yaml
Configure hook tries to read the SEV kernel
param file to detect if SEV is enabled or not.
kvm plug provide read access to the SEV kernel
param file. So add kvm as plug to configure
hook.
> Add read access to SEV kernel param file

- test-requirements.txt
- tox.ini
TICS scan requires installation of all
dependency packages. pytest is installed
from tox in tox tests, however TICS workflow
uses *requirements.txt to install dependencies.
Move pytest to test-requirements.txt
> Move pytest to test-requirements

- snap/snapcraft.yaml
Detection of AMD SEV requires snapd change [1]
The change will be part of snapd 2.68
Change assumes to snapd2.68
[1] https://github.com/canonical/snapd/pull/15033
> Change requirement of snapd version to 2.68

- pyproject.toml
Add setuptools-scm to build system. Wihtout
this change the subfolders are not copied
during the package build.
> Add setuptools-scm to build

- bin/pre-evacuation-setup-service
- openstack_hypervisor/hooks.py
- openstack_hypervisor/services.py
- snap/snapcraft.yaml
- templates/masakarimonitors.conf.j2
This PR introduces a new service that listens for a signal via UNIX socket from consul for graceful host shutdown and VM evacuation. The service, on receiving the shutdown signal, checks to see if there are any VMs running in the host, shuts off all of them and marks the host as down. This then triggers and completes the evacuation successfully via Masakari, ensuring high availability during host maintenance or failure.
Impact
This enhances automated recovery workflows and ensures that VM workloads are safely relocated if NIC is down.
> Added service for pre-evacuation-setup

- README.md
- openstack_hypervisor/hooks.py
- templates/nova.conf.j2
We'll allow setting the `pci.pci_passthrough_whitelist` n-cpu option, which can be used to expose PCI devices such as GPU devices or SR-IOV VFs.
The patch preserves the naming and description from the old reactive charm: https://opendev.org/openstack/charm-nova-compute/src/commit/25a0aba59d0b760b1c12b2c99c269aad80d2e087/config.yaml#L224-L236
> Define pci-passthrough-whitelist setting

- README.md
- openstack_hypervisor/cli/interfaces.py
- openstack_hypervisor/hooks.py
- openstack_hypervisor/pci.py
- tests/unit/test_pci.py
Sunbeam will allow setting global PCI whitelists and per-node exclusion lists.
This patch applies the configured exclusion lists, converting the whitelist to more granular PCI filters, leaving out excluded devices.
For example, let's say that the user whitelisted all Intel x550 devices and then excluded one out of 4 such interfaces:
```
pci_device_specs = [{"vendor_id": "8086", "product_id": "1563"}]
excluded_devices = ["0000:1b:00.1"]
```
The updated device spec will contain the vendor/product and pci address of the remaining 3 Intel x550 devies.
```
[
{"vendor_id": "8086", "product_id": "1563", "address": "0000:19:00.0"},
{"vendor_id": "8086", "product_id": "1563", "address": "0000:19:00.1"},
{"vendor_id": "8086", "product_id": "1563", "address": "0000:1b:00.0"},
]
```
Note that the …
> Allow excluding PCI devices

- templates/nova.conf.j2
Nova doesn't yet support tracking SR-IOV ports consumed by Neutron using the Placement service [1].
```
In nova 26.0.0 (Zed) the Placement resource tracking of PCI devices
does not support SR-IOV devices intended to be consumed via Neutron
ports and therefore having physical_network tag in pci.device_spec.
Such devices are supported via the legacy PCI tracker code path in Nova.
In Antelope flavor based PCI requests are supported but Neutron
port base PCI requests are not handled in Placement.
```
If `report_in_placement` is enabled, attempting to attach Neutron ports will fail.
```
Failed to allocate PCI devices for instance. Unassigning devices
back to pools. This should not happen, since the scheduler should
have accurate information, and allocation during claims is controlled
via a …
```
> Disable `report_in_placement` to allow SR-IOV Neutron ports

- openstack_hypervisor/cli/interfaces.py
- openstack_hypervisor/hooks.py
- openstack_hypervisor/pci.py
- snap/snapcraft.yaml
This PR makes the following SR-IOV related improvements:
* add `kernel-module-control` to libvirt
* required when attaching VFs with hardware offloading enabled
* modify the PCI whitelist, replacing PFs with individual VFs
* Nova no longer allows whitelisting PFs *and* their VFs
* Nova implicitly whitelists VFs only if the parent PF is whitelisted by name (deprecated) or address,  but not by product/vendor id
* Sunbeam will whitelist individual PFs, specifying the address and vendor/product id
* ensure that "list-nics" includes PF/VF devices that were already attached to openstack instances
* enumerate the pci devices and look for omitted network devices
* without this, attached VFs will no longer be included in nova.conf after subsequent runs of the configure hook
* be aware that those …
> SR-IOV improvements

- openstack_hypervisor/cli/interfaces.py
When using hw offloading, Nova expects the physnet to be None (null), not an empty string.
We'll update the snap to allow this.
> sriov: Allow physnet to be None

- openstack_hypervisor/cli/interfaces.py
- openstack_hypervisor/hooks.py
- openstack_hypervisor/pci.py
Backport of https://github.com/canonical/snap-openstack-hypervisor/pull/85
This PR makes the following SR-IOV related improvements:
* ~~add `kernel-module-control` to libvirt~~
* ~~required when attaching VFs with hardware offloading enabled~~
* modify the PCI whitelist, replacing PFs with individual VFs
* Nova no longer allows whitelisting PFs *and* their VFs
* Nova implicitly whitelists VFs only if the parent PF is whitelisted by name (deprecated) or address,  but not by product/vendor id
* Sunbeam will whitelist individual PFs, specifying the address and vendor/product id
* ensure that "list-nics" includes PF/VF devices that were already attached to openstack instances
* enumerate the pci devices and look for omitted network devices
* without this, attached VFs will no longer be …
> SR-IOV improvements (backport)

- openstack_hypervisor/hooks.py
- tests/unit/test_hooks.py
This change will determine if there are any whitelisted sr-iov nics that support hardware offloading (switchdev mode).
If so, we're setting the ovs 'other_config:hw-offload' ovs property.
> ovs: configure hw offloading

- openstack_hypervisor/devspec.py
- tests/unit/test_devspec.py
Sunbeam needs to check if a given PCI device is whitelisted.
The imlementation needs to be compatible with Nova, however we can't import Nova code since it's a large dependency and we can't copy Nova modules either since that could break the Canonical license agreement. Both projects are currently Apache 2 licensed, however the Canonical CLA demands re-licensing rights.
That being considered, we'll rewrite the devspec module, greatly simplifying it.
Nova no longer allows the pci device specs to include device names, we can drop that.
We'll also avoid explicitly checking if a device is a PF and rely solely on addresses. The advantage is that this can be used remotely, without querying any local devices.
(cherry picked from commit 918864d117984d6e9079a9169a65abd41c4ea4bb)
> Rewrite devspec module

- openstack_hypervisor/cli/common.py
- openstack_hypervisor/cli/interfaces.py
- openstack_hypervisor/cli/main.py
- openstack_hypervisor/hooks.py
- tests/unit/test_hooks.py
Snap values should not be access at import time, and should not be instantiated directly in helper method, ensure control propagation of the snap object.
> Ensure snap data is not access out of band

- templates/nova.conf.j2
We previously had some issues with SR-IOV devices and placement reporting. Nova docs also made it seem like this scenario is unsupported.
Those issues were addressed by explicitly whitelisting VFs instead of PFs
Sample: https://paste.ubuntu.com/p/vTg3GZVKz6/plain/
VFs that have an associated physnet will not be reported to the placement service, however they can still be attached, leveraging the old Nova PCI tracker.
Charm patch: https://review.opendev.org/c/openstack/sunbeam-charms/+/956772
> Enable pci.report_in_placement

- snap/snapcraft.yaml
Attaching ports with hardware offloading currently fails as Libvirt attempts to load the VF driver:
Failed to load PCI driver module mlx5_vfio_pci: modprobe:
ERROR: could not insert 'mlx5_vfio_pci': Operation not permitted
To address this, we'll leverage the "kernel-module-control" snap interface.
We previously reverted this change in order to do some further testing after experiencing some inconsistent snap behavior. However, it turns out that we really need this plug in order for hardware offloading to work.
> libvirt: add "kernel-module-control" plug

- README.md
- openstack_hypervisor/hooks.py
- snap/snapcraft.yaml
- tests/unit/test_hooks.py
This PR will allow configuring OVS to use DPDK, introducing the following settings:
* `network.ovs-dpdk-enabled`: specifies whether ovs should initialize DPDK support
* `network.ovs-memory`: comma separated list of integers that represent the memory (in MB) from each numa node to be used by OVS for DPDK
* `network.ovs-pmd-cpu-mask` bit mask specifying which CPUs should be used by OVS to run the PMD threads. For example, 0xF0 would enable the 5,6,7,8 cores.
* `network.ovs-lcore-mask` bit mask specifying which CPUs should be used by OVS to run the lcore threads. For example, 0xF0 would enable the 5,6,7,8 cores.
If DPDK is enabled, the OVS bridges will be set to use the `netdev` data path instead of `system.
At the same time, we'll enable `vhost-user` support when building Qemu.
neutron-k8s …
> Add DPDK support

- openstack_hypervisor/hooks.py
- tests/unit/test_hooks.py
We currently allow enabling dpdk but we aren't modifying the "dpdk-init" setting if dpdk is subsequently disabled by the user.
This change will explicitly set "dpdk-init" to "false" if DPDK is disabled or unavailable.
The other DPDK settings will be ignored by OVS if DPDK is disabled.
> Allow disabling dpdk

- snap/snapcraft.yaml
This PR adds the snap permissions required for physical DPDK port handling, introduced here:
https://github.com/canonical/snap-openstack-hypervisor/pull/111
We're using a separate PR since the new privileges will have to be approved by the snap team.
We need to hold this until the following request gets approved: https://forum.snapcraft.io/t/request-network-setup-control-and-system-files-openstack-hypervsior-snap/48415
> Add DPDK snap permissions

- snap/snapcraft.yaml
Binary data such as `seabios.bin` or `kvmvapic.bin`, which are necessary for more advanced features of nova/libvirt/qemu are missing from the hypervisor.
Include the package `qemu-system-data` instead of building because:
- package has not dependency, only brings bios binaries
- build the binaries requires the correct git submodules setup, which are not available directly from the debian package repo
- no value in being rebuilt specifically for the snap
> Ensure qemu binary data is available in the snap

- bin/pre-evacuation-setup-service
- openstack_hypervisor/hooks.py
- openstack_hypervisor/services.py
- snap/snapcraft.yaml
- templates/masakarimonitors.conf.j2
BACKPORT Masakari TCP Health check to caracal
- Added a Unix domain socket listener service to handle external VM shutdown commands
- Integrated nova-compute stop and virsh shutdown logic for safe instance evacuation
- Introduced timeout handling for VM shutdowns to ensure robustness
- Refactored and improved logging for better observability
- Added monitoring sample config under [host] group
- Set correct permissions, paths, and snap plugs/slots to enable service communication
(cherry picked from commit c4eef0e0bb7604fda9c818734a131a22f9fa33fa)
> [BACKPORT TO CARACAL] Implement VM shutdown listener with socket interface and monitoring
